[LVL9] Output level: 9
[INFO] Number of examples: 4
[DEBUG] 
[DEBUG] Processed Atoms:
[DEBUG] 	lfi_prob(0,t)::lfi_fact(0,X); lfi_prob(1,t)::lfi_fact(1,Y); lfi_prob(2,t)::lfi_fact(2,Z) :- lfi_rule(0_1_2,X,Y,Z)
[DEBUG] 	lfi_rule(0_1_2,X,Y,Z) :- X<Y, Y=Z+1, between(1,4,X), between(1,4,Y)
[DEBUG] 	a(X) :- lfi_body(0,X)
[DEBUG] 	lfi_body(0,X) :- lfi_par(0,X), lfi_fact(0,X)
[DEBUG] 	lfi_par(0,X) :- lfi_rule(0_1_2,X,Y,Z)
[DEBUG] 	b(Y) :- lfi_body(1,Y)
[DEBUG] 	lfi_body(1,Y) :- lfi_par(1,Y), lfi_fact(1,Y)
[DEBUG] 	lfi_par(1,Y) :- lfi_rule(0_1_2,X,Y,Z)
[DEBUG] 	c(Z) :- lfi_body(2,Z)
[DEBUG] 	lfi_body(2,Z) :- lfi_par(2,Z), lfi_fact(2,Z)
[DEBUG] 	lfi_par(2,Z) :- lfi_rule(0_1_2,X,Y,Z)
[DEBUG] 
[DEBUG] Base Program:
[DEBUG] 	body_2(0,multi,V_0,V_1,V_2) :- lfi_rule(0_1_2,V_0,V_1,V_2).
[DEBUG] 	lfi_rule(0_1_2,V_0,V_1,V_2) :- V_0<V_1, V_1=V_2+1, between(1,4,V_0), between(1,4,V_1).
[DEBUG] 	a(V_0) :- lfi_body(0,V_0).
[DEBUG] 	lfi_body(0,V_0) :- lfi_par(0,V_0), lfi_fact(0,V_0).
[DEBUG] 	lfi_par(0,V_0) :- lfi_rule(0_1_2,V_0,V_1,V_2).
[DEBUG] 	b(V_0) :- lfi_body(1,V_0).
[DEBUG] 	lfi_body(1,V_0) :- lfi_par(1,V_0), lfi_fact(1,V_0).
[DEBUG] 	lfi_par(1,V_0) :- lfi_rule(0_1_2,V_1,V_0,V_2).
[DEBUG] 	c(V_0) :- lfi_body(2,V_0).
[DEBUG] 	lfi_body(2,V_0) :- lfi_par(2,V_0), lfi_fact(2,V_0).
[DEBUG] 	lfi_par(2,V_0) :- lfi_rule(0_1_2,V_1,V_2,V_0).
[DEBUG] 	lfi_prob(0,t)::lfi_fact(0,V_0); lfi_prob(1,t)::lfi_fact(1,V_1); lfi_prob(2,t)::lfi_fact(2,V_2) :- body_2(0,multi,V_0,V_1,V_2).
[DEBUG] 	
[DEBUG] AD Groups		:[(a(X), b(Y), c(Z))]
[DEBUG] 
[DEBUG] Compiling example 1/4
[DEBUG] 	Grounded Atoms:	(b(2), a(1), c(3))
[DEBUG] 	Evidence:	[(b(2), True), (a(1), True), (c(3), True)]
[ERROR] 
[ERROR] Error encountered:	
[ERROR] Traceback (most recent call last):
[ERROR]   File "/Users/arcchit/Docs/problog/problog/learning/lfi.py", line 1571, in main
[ERROR]     results = run_lfi(program, examples, knowledge=knowledge, **options)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/learning/lfi.py", line 1425, in run_lfi
[ERROR]     score = lfi.run()
[ERROR]   File "/Users/arcchit/Docs/problog/problog/learning/lfi.py", line 1008, in run
[ERROR]     self.prepare()
[ERROR]   File "/Users/arcchit/Docs/problog/problog/learning/lfi.py", line 253, in prepare
[ERROR]     self._compile_examples()
[ERROR]   File "/Users/arcchit/Docs/problog/problog/learning/lfi.py", line 534, in _compile_examples
[ERROR]     example.compile(self, baseprogram)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/learning/lfi.py", line 1076, in compile
[ERROR]     propagate_evidence=lfi.propagate_evidence,
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine.py", line 56, in ground
[ERROR]     return ground_default(model, target, **kwdargs)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine.py", line 89, in ground_default
[ERROR]     labels=labels,
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine.py", line 579, in ground_all
[ERROR]     db, target, evidence, propagate_evidence=propagate_evidence
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine.py", line 494, in ground_evidence
[ERROR]     is_root=True,
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine.py", line 336, in ground
[ERROR]     target, results = self._ground(db, term, target, silent_fail=False, **kwdargs)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine.py", line 452, in _ground
[ERROR]     clause_node, database=db, target=gp, context=context, **kwdargs
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 684, in execute
[ERROR]     next_actions = self.eval(obj, **context)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 212, in eval
[ERROR]     return exec_func(node_id=node_id, node=node, **kwdargs)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 1078, in eval_call
[ERROR]     node.defnode, parent=parent, identifier=identifier, **kwdargs
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 212, in eval
[ERROR]     return exec_func(node_id=node_id, node=node, **kwdargs)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 1197, in eval_builtin
[ERROR]     return self.eval_default(EvalBuiltIn, **kwdargs)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 1201, in eval_default
[ERROR]     cleanup, actions = node()  # Evaluate the node
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 2475, in __call__
[ERROR]     current_clause=self.current_clause
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_stack.py", line 2500, in __call__
[ERROR]     if self.base_function(*args, **kwdargs):
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_builtin.py", line 814, in _builtin_lt
[ERROR]     check_mode((arg1, arg2), ["gg"], functor="<", **kwdargs)
[ERROR]   File "/Users/arcchit/Docs/problog/problog/engine_builtin.py", line 627, in check_mode
[ERROR]     raise CallModeError(functor, args, accepted, location=location)
[ERROR] problog.engine_builtin.CallModeError: Invalid argument types for call to '</2': arguments: (X1, 2), expected: (ground, ground).
[ERROR] 
